### ISSUE TITLE
Font color selection

### ISSUE THREAD

**Issue by ohine** [DNN-Connect/CKEditorProvider#10]
When changing the font color of selected text, an extra closing tag is added and the color is applied incorrectly.

**Comment by valadas** [comment]
I cannot reproduce in Dnn 9.7.1, I get this:
```
<p>Lorem <span style="color:#00923E">Ipsum</span></p>
```

If this is still relevant, please open a new issue with more details on how to reproduce, we are moving this project there with https://github.com/dnnsoftware/Dnn.Platform/pull/4096
