### ISSUE TITLE
Height must be non negative Error 

### ISSUE THREAD

**Issue by chadwixk** [DNN-Connect/CKEditorProvider#101]
I'm using the DNN Announcements module in DNN 9.2.2 and trying to add a new announcement throws this error:

`An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Height must be non negative. Parameter name: value ---> System.ArgumentOutOfRangeException: Height must be non negative. Parameter name: value at System.Web.UI.WebControls.Style.set_Height(Unit value) at System.Web.UI.WebControls.WebControl.set_Height(Unit value) at DNNConnect.CKEditorProvider.CKHtmlEditorProvider.set_Height(Unit value) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---`

I've checked the Editor Height setting in the config section on DNN. It was originally just 200. I tried adding the 'px' (200px), along with a %, etc. to no avail. Any ideas?

Other instances that use this editor (like editing the content on an HTML module) works ok.

![ckeditor](https://user-images.githubusercontent.com/5115308/51567729-2d258d80-1e55-11e9-81b3-91ea3fdb8198.PNG)

**Comment by sleupold** [comment]
I noticed similar errors on DNN 9.2.2 -  and the CK Version of the provider was outdated.
I switched to the original provider (https://github.com/w8tcha/dnnckeditor), which seems to be better maintained.

**Comment by sleupold** [comment]
btw. I wouldn't use DNN Announcements module in new websites - there are better alternatives meanwhile

**Comment by chadwixk** [comment]
Thanks Sebastian!  I'll check out w8tcha's version. I actually posted this issue on his Git project page first, and he sent me over here :)

Curious which announcements module? I see you only have DNN.Announcements listed at https://github.com/sleupold/awesome-dnn

**Comment by chadwixk** [comment]
Drats, changed to w8tch's version...same basic error. 

`An error has occurred. DotNetNuke.Services.Exceptions.ModuleLoadException: Height must be non negative. Parameter name: value ---> System.ArgumentOutOfRangeException: Height must be non negative. Parameter name: value at System.Web.UI.WebControls.Style.set_Height(Unit value) at System.Web.UI.WebControls.WebControl.set_Height(Unit value) at DNNConnect.CKEditorProvider.CKHtmlEditorProvider.set_Height(Unit value) at DotNetNuke.UI.UserControls.TextEditor.OnLoad(EventArgs e) --- End of inner exception stack trace ---`

Must be the way DNN.Announcements implements the editor? Not passing the proper arguments? I don't know. The ascx files don't really specify any parameters when listing the editor inline code. So not sure why its only an issue in this Announcements module.

**Comment by ohine** [comment]
@chadwixk I'd be very careful if you do choose to use the original provider on any public facing sites. The official provider has had a few security reviews and we've fixed quite a few major security vulnerabilities, I'm not positive if @w8tcha has fixed them as well in his version. Also, in a perfect world we wouldn't have two versions. It would be awesome if we could join forces with Ingo and consolidate the providers to a single maintained version.

**Comment by chadwixk** [comment]
@ohine  thanks for the info. Yes, I'd agree on merging. From a user perspective that has not used DNN actively since v6.0, now coming back to it for a project, it is extremely difficult now to get a Community version up and running like you could before with all the DNN Forge modules. Now all those modules are all over the place, in various states of being maintained, incompatibility issues, etc. It has been very frustrating to say the least.

**Comment by ohine** [comment]
I completely agree, and it's something the TAG group is working on cleaning up.

**Comment by chadwixk** [comment]
Finally fixed the error. Changing the height from 99% to 400px in it's default settings worked.
![editor](https://user-images.githubusercontent.com/5115308/51575220-877f1800-1e6e-11e9-9c9f-bb2b80782ebc.PNG)

**Comment by chadwixk** [comment]
Figured it out. Was a setting in the DNN.Announcements for that module. Somehow it was set to -1. Changed to 400px, works.
![editor](https://user-images.githubusercontent.com/5115308/51575444-58b57180-1e6f-11e9-8563-973b8b5a688e.PNG)
