### ISSUE TITLE
ML Link Portal Page in wrong language

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNN-Connect/CKEditorProvider#103]
DNN 9.2.2 (CK editor 01.00.04)
On a site with languages, nl-NL (default)  & en-US & Content Localization switched on.
On a translated page.
When I edit a text (HTML module) and add a link.
In the popup I select "Portal Page" as the "Link Type".
The dropdown now shows pages in the default language, not the current language.
So in my case, always nl-NL never en-US.

I would expect it to show the pages in the current page's language. :-)

**Comment by Timo-Breumelhof** [comment]
FYI, I have this one one installation on another it seems to work fine. We'll try to find out what the difference is.

**Comment by Timo-Breumelhof** [comment]
The site with the issue has DNN edit popups switched off, when I switched them back on the issue remains the same.

**Comment by valadas** [comment]
We are moving this project to the main Platform repository, if this is still an issue on current version, please open a new issue at https://github.com/dnnsoftware/Dnn.Platform and add some more details in the steps to reproduce section of the issue template, this may be only reproducible with some settings and it would be nice to have steps to get to those settings (portal alias setup comes to mind, portal groups, friendly url settings and so on). Thanks.
