### ISSUE TITLE
Is this repo based on Watchers.NET CKEditorProvider code? 

### ISSUE THREAD

**Issue by roman-yagodin** [DNN-Connect/CKEditorProvider#11]
So the question: is this repo based on Watchers.NET CKEditorProvider code?

**Comment by ohine** [comment]
It is

**Comment by roman-yagodin** [comment]
Well, not see any reference about it in the license or readme.

**Comment by ohine** [comment]
https://github.com/DNN-Connect/CKEditorProvider/blob/development/Install/DNNCkeditor.license.txt

**Comment by ohine** [comment]
https://github.com/DNN-Connect/CKEditorProvider/blob/development/Install/releaseNotes.txt#L18

**Comment by roman-yagodin** [comment]
Sorry, missed that :+1:
