### ISSUE TITLE
CKEditor custom Keystrokes doesn't work

### ISSUE THREAD

**Issue by berkarslan-xo** [DNN-Connect/CKEditorProvider#123]
## Description of bug
When trying to edit the CKEditor config to use the custom keystroke [CKEDITOR.CTRL + 75 /*K*/, 'link' ] which is wanted for the hyperlink, it doesn't work.

## Steps to reproduce
List the steps to reproduce the behavior:
- Open HTML Editor Manager. Persona bar > Site Settings > Site Behaviour > More > 
- Add a new value in Keystroke field e.g. [ CKEDITOR.CTRL + 75 /*K*/, 'link' ] 
- Save

## Current result
- The shortcut that is added to work as a link in HTML editor won't work 
- Also, not able to see the previously added Kerstroke value.

## Expected result
- The keystroke should work. 

## Affected version

* [ ] 10.0.0 nightly build
* [ ] 9.4.1 nightly build
* [ ] 9.4.0 release candidate
* [x] 9.3.2 latest supported release

## Affected browser

* [x] Chrome
* [x] Firefox
* [x] Safari
* [x] Internet Explorer
* [x] Edge

**Comment by valadas** [comment]
@mitchelsellers Do we set the version here to 9.5.0 and a milestone to track for the release notes?
