### ISSUE TITLE
Edit HTML Module removes options from DIV

### ISSUE THREAD

**Issue by thabaum** [DNN-Connect/CKEditorProvider#135]
I know there are some security features in the editor and one is removing options from a div each time I open.  But when I save it works ok.  Not much of a security feature really more of a bug.   Should stop it from being saved, not from being opened to view the source.

https://github.com/dnnsoftware/Dnn.Platform/issues/3370

I reported the issue above and it relates to this project so I put in another issue here.

Not end of the world just something that causes a lot of extra work.

**Comment by w8tcha** [comment]
Can be easily fixed you only need to define a rule in the ACF. In the Editor Settings under Editor Config > **ExtraAllowedContent** enter..

`div[data-*]`

this would allow data attributes inside div tags.  This should resolve the issue

**Comment by valadas** [comment]
We are moving this project to the main platform repository and I think this issue is the same as https://github.com/dnnsoftware/Dnn.Platform/issues/4102 if not, please open a new issue there as I am closing this one here.
