### ISSUE TITLE
The CKE editor will let the client validator not working

### ISSUE THREAD

**Issue by zyhfish** [DNN-Connect/CKEditorProvider#136]
Reproduce Steps:
1. install dnn latest version and login as host;
2. create a new module;
3. edit the module source to including:
a. a text box will a required validator;
b. a ck editor field;
c. a link button to submit the form;
4. browse to the new module, DO NOT input anything in the textbox field but just click the submit button.

Expected Result:
the page should not reload, but just display the error message.

Actually Result:
post back data will send to the server and page get reload.

**Comment by v-karbovnichy** [comment]
@mitchelsellers can you check the PR #137 ?
