### ISSUE TITLE
Image Editor

### ISSUE THREAD

**Issue by thenotandy** [DNN-Connect/CKEditorProvider#145]
Does anyone know what would it take to get an image editor like the one https://github.com/w8tcha/dnnckeditor uses?

**Comment by valadas** [comment]
It would take a developer to implement it.
We are moving this project to https://github.com/dnnsoftware/Dnn.Platform if anyone as the intention to implement such editor, please open a discussion at here https://github.com/dnnsoftware/Dnn.Platform/discussions first and upon agreement and a volunteer, we can then make it an issue there. Thanks.
