### ISSUE TITLE
Editing in HTML module doesn't show files for image manager

### ISSUE THREAD

**Issue by andyduo** [DNN-Connect/CKEditorProvider#146]
I'm reporting a bug (I think) and reference an issue on the main DNN GitHub. There is an issue where the image manager does not display the images in the root folder of the site. I suspect this was introduced with 1.07 version of the editor as I cannot reproduce on sites that use earlier versions.

Users are able to create sub directories and upload to those folders and view the images within them. You can still upload to the root folder but cannot see any of the contents.

Here is the original bug report which contains a fair bit of info on what people have experienced and tried as fixes: [https://github.com/dnnsoftware/Dnn.Platform/issues/3004](https://github.com/dnnsoftware/Dnn.Platform/issues/3004)

I have a test site on my server that I can give access to if it helps with understanding the behavior.

**Comment by andyduo** [comment]
Upgraded my test site to  DNN 9.7.1 but still have this problem. Unsure how to fix it but can't upgrade any of my DNN sites since early v9 as they all end up with this problem.

**Comment by valadas** [comment]
Sorry for the bouncing around, but we are moving this project into the main repository soon, so I am closing this issue in favor of the original one at https://github.com/dnnsoftware/Dnn.Platform/issues/3004
