### ISSUE TITLE
No "Portal Page" with relative URL possible anymore when using HTTPS

### ISSUE THREAD

**Issue by a-git-hub** [DNN-Connect/CKEditorProvider#148]
Good evening, 

we started working only with sites which have HTTPS like **https://web.blabla.int/**, as this is what now all sites have, and are not able to use such an important feature of the DNN CKEditor as "Link -> **Portal Page: Page from within your Portal**" anymore.  
Because it now produces only absolute URLs in the result:

![CKEditor-HTTPS-Link-PortalSite-Problem2-2020](https://user-images.githubusercontent.com/20930019/92998310-62468e00-f519-11ea-86b2-ce47444bc8bf.jpg)

The detailed description of the problem is here: 
https://github.com/dnnsoftware/Dnn.Platform/issues/2317

We can add one more additional screenshot, what you see if you search for alternative ways and try to link to an internal page through the "Seiten Link": 
![CKEditor-HTTPS-Link-PortalSite-Problem-2020](https://user-images.githubusercontent.com/20930019/92997971-696c9c80-f517-11ea-8ea3-84d647844388.jpg)
In it one can see, that the Domain name is now appearing also in "Relative URL" and two times(!) in "Absolute URL".

It would be great if you could fix this soon.

We use: 

- DNN PLATFORM v. 09.03.02 
- CKEditor Editor Provider (CKEditor Editor Provider for DNN): 2.1.27
- DNN Connect CKEditor Provider (CKEditor Provider by DNN Connect for DNN): 1.0.5
- CKEditor Config Manager (Configuration Manager for the CKEditor Editor Provider): 2.1.27

**Comment by valadas** [comment]
Was this tested in the latest release of Dnn with the editor that comes with it?

**Comment by a-git-hub** [comment]
We have over 20 sites with DNN with many users and on all of them we use DNN PLATFORM v. 09.03.02. Update to a higher DNN version would be problematic or even impossible because of the modules which we installed.

**Comment by mitchelsellers** [comment]
Sadly, from a support perspective, we are ONLY working with current versions of the DNN Platform for ongoing support.

I STRONGLY encourage everyone to get to the latest version of DNN as soon as practical due to the number of security fixes that are included.  

I have attempted to recreate this issue with the current release and am not able to.

**Comment by a-git-hub** [comment]
Hello @mitchelsellers, you tested it with the "CKEditor Editor Provider" version 2.1.27 ?

**Comment by mitchelsellers** [comment]
I used the current version of this provider 1.1.0

**Comment by valadas** [comment]
I am closing this issue because:
1. It was not reproducible in currently supported releases
2. We are moving this project to the main repository at https://github.com/dnnsoftware/Dnn.Platform

@a-git-hub if you still have this issue on current release, please open a new issue there. Thanks.
