### ISSUE TITLE
Define global paths

### ISSUE THREAD

**Issue by jbrinkman** [DNN-Connect/CKEditorProvider#2]
Currently there are a number of file paths which are hard-coded throughout the codebase.  This makes the code very brittle if the folder structure changes again.  The code should be refactored to reference global pathing variables so that path strings can be managed in a single code location.

**Comment by valadas** [comment]
With https://github.com/dnnsoftware/Dnn.Platform/pull/4096 we will be merging this project into the platform repository, I see a commit referenced this issue and I am assuming this was the fix, if not please reopen an issue in the main repository with some details on where paths are hardcoded. thanks.
