### ISSUE TITLE
Selecting js or xml file in provider's config doesn't work at all

### ISSUE THREAD

**Issue by moshefi** [DNN-Connect/CKEditorProvider#24]
Also, since the urlcontrol uses dnn's functions it is impossible to see js files in the list.
You must enable js in host allowed extensions and that's a security problem.

It is needed for custom config & templates file selection.

**Comment by ghost** [comment]
It seems this is still an issue with the current version including w8tcha DNN CK provider. Would be nice if this gets fixed.

**Comment by sleupold** [comment]
AFAIK the config is intendedly taken from settings table in the database.

**Comment by ghost** [comment]
I understand but this means that anything outside of the standard will not be possible. I now changed the core js file to get what I need, that worked.

**Comment by valadas** [comment]
This issue has almost 3 years and 2 commits reference it. I am assuming it is resolved but was not closed. If I am wrong, we are moving this repository to the Platform repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096 so if this is still relevant, please open a new issue there with some steps to reproduce, I am not sure how js and xml files _should_ be referenced and an example of the use case would be nice in figuring out a fix. Thanks.
