### ISSUE TITLE
The "this portal only" option in the config has no effect

### ISSUE THREAD

**Issue by moshefi** [DNN-Connect/CKEditorProvider#25]
There is NO actual solution for host configuration options the config.

**Comment by valadas** [comment]
I was not able to reproduce this issue in dnn 9.7.1

We are moving this project into the Platform repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096 if this issue is still relevant, please open a new issue there with a bit more details or steps to reproduce. Thanks.
