### ISSUE TITLE
site build failed in vs after install ck editor package

### ISSUE THREAD

**Issue by zyhfish** [DNN-Connect/CKEditorProvider#65]
after install ck editor package into site, then open the site in visual studio and start to build the site, you will get build error which comes from:
1. Providers\HtmlEditorProviders\DNNConnect.CKE\CKFinder\config.ascx;
2. Providers\HtmlEditorProviders\DNNConnect.CKE\js\ckeditor\4.5.3\plugins\newsarticleslinks\dialogs\newsarticleslinks.aspx.cs

Expected Result:
the website can build successful with ck editor installed.

**Comment by zyhfish** [comment]
PR submitted: https://github.com/DNN-Connect/CKEditorProvider/pull/66

**Comment by hoanhnv** [comment]
Hey you, How do you resolve this issue?
I can not build from source with visual studio.
pls help me.
