### ISSUE TITLE
Inline width/height - as it relates to images

### ISSUE THREAD

**Issue by hallmatt** [DNN-Connect/CKEditorProvider#72]
When you insert an image, the height and width are automatically added to the width/height boxes in the "Image Properties" dialog. Then, when you hit "ok", these styles are added as inline styles, for example:

```
<img src="/path/to/image.jpg" style="width:100px;height:100px;" />

```

This is problematic when attempting to adhere to a mobile-first strategy, since the inline style easily overrides any CSS that's been added to try and format images properly for mobile. 

The default functionality when adding an image should cause no inline styles for width/height, unless the end-user tweaks the values to something different than what the original image contains.

**Comment by sleupold** [comment]
this sounds like an issue of the editor itself, not the provider
would you mind to check with dkEditor (https://github.com/ckeditor/ckeditor-dev/issues)

**Comment by hallmatt** [comment]
Wow. I forgot about this one. Sad to see a year go by without any comment by a contributor to the project, but it seems to be the status quo for all things DNN. We've moved on to a different CMS. Thanks for responding anyway @sleupold and directing me to the right spot. You've always been a rockstar in the community. Many thanks!
