### ISSUE TITLE
trouble building the solution

### ISSUE THREAD

**Issue by GusBeare** [DNN-Connect/CKEditorProvider#82]
I can't seem to build the solution. Just get loads of references errors. Can anyone help me out or provide the install.zip package instead?

This kind of thing: 

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0246	The type or namespace name 'DotNetNuke' could not be found (are you missing a using directive or an assembly reference?)	DNNConnect.CKEditorProvider	C:\Users\gus\Downloads\CKEditorProvider-1.0.3\CKEditorProvider-1.0.3\Browser\Browser.aspx.cs	22	Active

But the references to the DNN dlls seem fine.

**Comment by GusBeare** [comment]
Weird, changing the target .Net version from 4 to 4.5 fixed the references issue for me and I was able to build.

Would it be possible to include the .zip package with releases in future?

**Comment by sleupold** [comment]
the latest install package should be included with the DNN install and upgrade packages (in /install/Provider Folder)

**Comment by Xand0r** [comment]
Is there a reason that the most recent version of this module is not available for download as an installer here? https://github.com/DNN-Connect/CKEditorProvider/releases

**Comment by valadas** [comment]
We are moving this project to the main repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096 so the build instructions will be the build instructions will be https://github.com/dnnsoftware/Dnn.Platform/blob/develop/.github/BUILD.md

Please give it a few days for that PR to merge and for adjusting the build process but before the next Dnn release we will have it building there.
