### ISSUE TITLE
where is the mathjax extension

### ISSUE THREAD

**Issue by azarbara** [DNN-Connect/CKEditorProvider#85]
the mathjax extension can't active in ckeditor. 
do you have any plan to add add-on s to ckeditor?

**Comment by valadas** [comment]
I am closing this issue since it was unanswered for a long time, as far as I know this is not part of the normal distribution and would be an additional plugin. Please follow this issue about how to integrate plugins https://github.com/dnnsoftware/Dnn.Platform/issues/4100
