### ISSUE TITLE
Update CKEditor

### ISSUE THREAD

**Issue by bdukes** [DNN-Connect/CKEditorProvider#87]
Does anyone (@ohine?) know what needs to be done to get CKEditor updated?  This extension is using 4.5.3, and there is a 4.5.11, a 4.8, and it looks like CKEditor 5 is currently in alpha

**Comment by sleupold** [comment]
FYI: https://github.com/w8tcha/dnnckeditor/releases does include latest version of CKEditor 4.

**Comment by astrodata** [comment]
w8tcha version seems not to be maintained and updated anymore.

**Comment by TopCat6** [comment]
I'm trying to find out if CKEditor 5 will be in DNN 10.0.  If not, is there a way to make CKEditor 4 generate responsive code for image files with img tag?

**Comment by valadas** [comment]
Moving this to https://github.com/dnnsoftware/Dnn.Platform/issues/4101
