### ISSUE TITLE
Question: Is there a way to set the Editor Area CSS in the settings XML?

### ISSUE THREAD

**Issue by OllyHodgson** [DNN-Connect/CKEditorProvider#90]
Question is as per the title: Is there a way to set the editor area CSS file in Dnn.CKEditorSettings.xml?

When I export my settings, that doesn't appear to be included in the XML file.

Many thanks,
Olly Hodgson.

**Comment by Timo-Breumelhof** [comment]
AFAIK the only way is to pass custom settings as described here: https://opencontent.readme.io/docs/field-types#section-rich-text-with-ckeditor IIRC this is because of the way the DNN CKeditor is loaded, which limits that options for OC.
