### ISSUE TITLE
AbsoluteURL

### ISSUE THREAD

**Issue by in8dna** [DNN-Connect/CKEditorProvider#91]
See: http://www.dnnsoftware.com/answers/ckeditor-absoluteurl-setting

AbsoluteUrl value is in DNN 8.0.4 databases. They have the default DNNConnect.CKE v1.0.3 but module content edited always reverts to relativeUrl

I see the behavior across all portals and on any module I require an absolute path (which happens to be the same url as the portal the module is using). When the Absolute URL is to a remote Url (like wikipedia) it maintains the AbsoluteUrl as Expected. But not when the Link Url happens to be the local Url.

**Comment by rdh755** [comment]
I'm still seeing the same behavior on DNN 9.3.3 utilizing DNNConnect.CKE v1.0.5. Our issue a bit separate. Looks like the Editor is utilizing Absolute urls but in our dbs and XML scripts we have the value as RelativeUrl. Seeing this behavior across our portals and on modules that utilize CKEditor.

The setting works when implementing a portal file or other url, the link is created as expected. However, when creating a link using portal page, it pulls down a dropdown of page items with absolute url values.

Funny thing is this, when I check the CKEditor settings on a local instance, the DefaultLinkMode is set to RelativeURL. When I click update, and refresh the module, I see that the portal page utilizes RelativeURLs. If it's one instance w/ a couple of portals, I would suggest hitting each portal instance CKEditor setting and hit update, but I'm dealing w/ a lot of portals w/ the same issue.

**Comment by in8dna** [comment]
There's a tip worth trying. I have noticed that a single one of the portals have worked as expected. I wonder if that is because of the 'save settings' for this portal vs 'save settings' for ALL portals.

Thanks for contributing. I'll check it out.

My work-around has been to use absolute paths in the HTML editing with a URL that is NOT in the DNN db alias table, but rather - on IIS as a valid URL for the website. img src="https://core.url.com" or img src="https://portal03.URL.com"

**Comment by rdh755** [comment]
If it's the save settings could be an issue w/ DNN and CKEditor not interacting as expected? Some sort of Caching issue?

**Comment by valadas** [comment]
This issue had no comments for about a year. We are moving this project to the main Platform repository with https://github.com/dnnsoftware/Dnn.Platform/pull/4096

If this is still an issue, please open a new issue there and you can reference this one.
