### ISSUE TITLE
Too easy to delete a toolbar

### ISSUE THREAD

**Issue by dnndiva** [DNN-Connect/CKEditorProvider#95]
Not an issue, but a improvement request dearly needed. It is simply too easy to delete a toolbar. The icons for edit and delete are very small and very close to each other, and on the top of that a "**Are you sure you want to delete this toolbar?**" message for a deletion confirmation is a must.

**Comment by valadas** [comment]
I am closing this issue since nobody picked it up in almost 2 years. If anyone is willing to implement this enhancement, please open a new issue at https://github.com/dnnsoftware/Dnn.Platform as we are moving this project to the main repository.
